// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/context/AuthProvider";
import { UserAuthProvider } from "@/context/UserContext";
import { ProductProvider } from "@/context/ProductContext";
import { CartProvider } from "@/context/CartContext";
import LayoutWrapper from "@/components/LayoutWrapper"; // New client wrapper
import { WishlistProvider } from "@/context/WisListContext";
import { Oswald, Roboto } from 'next/font/google'
import { CustomerProvider } from "@/context/CustomerProvider";
import { OrderProvider } from '@/context/OrderContext'
const oswald = Oswald({ subsets: ['latin'], weight: ['400', '700'], variable: '--font-oswald' })
const roboto = Roboto({ subsets: ['latin'], weight: ['400', '500'], variable: '--font-roboto' })
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Subhan Engraving Leather Works",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${oswald.variable} ${roboto.variable}`}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen`}>
        <AuthProvider>
          <UserAuthProvider>
            <ProductProvider>
              <CartProvider>
                <WishlistProvider>
                  <CustomerProvider>
                    <OrderProvider>
                      <LayoutWrapper>{children}</LayoutWrapper>
                    </OrderProvider>
                  </CustomerProvider>
                </WishlistProvider>
              </CartProvider>
            </ProductProvider>
          </UserAuthProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
